version: '3.8'

services:
#  postgres:
#    image: postgres:14
#    container_name: my_postgres
#    environment:
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#      POSTGRES_DB: mydatabase
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - my_network

  redis:
    image: redis:7
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - my_network

volumes:
#  postgres_data:
  redis_data:

networks:
  my_network:
    driver: bridge
